name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod vendor

    - name: Unit-Tests
      run: |
        # create the report directory
        mkdir -p report/
        # run the unit tests
        go test -v -short -covermode=count -coverprofile report/cover.out `go list ./...`

    - name: Lint
      run: |
        # install go lint
        pushd && go get golang.org/x/lint/golint && popd
        # add the GOBIN to the path
        export PATH="$PATH:$( go env GOPATH )/bin"
        # run the linter
        golint -set_exit_status `go list ./...`

    - name: Staticcheck
      run: |
        # install staticcheck
        pushd .. && go get honnef.co/go/tools/cmd/staticcheck && popd
        # add the GOBIN to the path
        export PATH="$PATH:$( go env GOPATH )/bin"
        # run staticcheck on the source code
        staticcheck `go list ./...`
